# Generated by Django 4.2.20 on 2025-04-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0048_student_shared_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offcampusexperience',
            old_name='experince_type',
            new_name='experience_type',
        ),
    ]
