# Generated by Django 4.2.20 on 2025-04-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0023_approvededucationalgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edcourse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
