name: Build and Push Container with Podman

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version in major.minor.patch format (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Validate version format
        run: |
          if ! echo "${{ github.event.inputs.version }}" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Error: Invalid version format. Use 'major.minor.patch' format (e.g., 1.2.3)."
            exit 1
          fi

      - name: Check current version in pyproject.toml
        id: check-version
        run: |
          CURRENT_VERSION=$(grep -oP '^version = "\K[^"]+' pyproject.toml)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "Current version: $CURRENT_VERSION"

      - name: Update version in pyproject.toml
        if: env.CURRENT_VERSION != github.event.inputs.version
        run: |
          echo "Updating version to ${{ github.event.inputs.version }} in pyproject.toml..."
          sed -i -E "s/^version = \".*\"/version = \"${{ github.event.inputs.version }}\"/" pyproject.toml
          echo "Version updated to ${{ github.event.inputs.version }} in pyproject.toml."

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version

      - name: Log in to GitHub Container Registry with Podman
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build container image with Podman
        run: |
          podman build -t ekiree-dashboard:${{ github.event.inputs.version }} .

      - name: Tag and push container image with Podman
        run: |
          podman tag ekiree-dashboard:${{ github.event.inputs.version }} ghcr.io/ekiree-technology/ekiree-dashboard:${{ github.event.inputs.version }}
          podman push ghcr.io/ekiree-technology/ekiree-dashboard:${{ github.event.inputs.version }}

      - name: Commit version changes
        if: env.CURRENT_VERSION != github.event.inputs.version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pyproject.toml
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          git push
