name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    
    - name: Install Flake
      run: | 
        nix build
        nix flake check

    - name: Run Tests
      run: |
        ./results/binpython ekiree_dashboard/manage.py test
