name: publish docker container

on: [push]

jobs:
  publish-ekiree-dashboard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry

    uses: docker/login-action@v1

    with:

    registry: ghcr.io

    username: ${{ github.actor }}

    password: ${{ secrets.GITHUB_TOKEN }}

    run: |

           docker build . --tag ghcr.io/ekiree-technology/ekiree-dashboard:latest

           docker run ghcr.io/ekiree-technology/ekiree-dashboard:latest

           docker push ghcr.io/ekiree-technology/ekiree-dashboard:latest



